### ISSUE TITLE
Images and fonts in less files are not downloaded

### ISSUE THREAD

**Issue by gioele** [cceh/atom#3]
The CSS files reference HTTP resources that cannot be accessed, for example

```
http://localhost:2234/plugins/arMeaStylePlugin/css/less/images/UzK_Logo.png
```

or

```
http://localhsot:2234/plugins/arMeaStylePlugin/vendor/fonts/Istok/2koEo4AKFSvK4B52O_Mwaha1RVmPjeKy21_GQJaLlJI.woff
```

This is probably due to the fact that rules with paths like

``` css
#mainLogo {
    background-image: url("images/UzK_Logo.png");
}
```

are compiled by LESS to

``` css
#mainLogo{background-image:url("less/images/UzK_Logo.png");
```

Maybe LESS is trying to be too smart and wants to preserve the directory structure?

/cc @strec
